version: '3'

services:
  app:
    image: golang
    build: 
      context: ./
    container_name: graphql
    volumes:
      - ./:/usr/src/app
    tty: true
    working_dir: /usr/src/app
    ports:
      - "8080:8080"